export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    analytics: "Analytics",
    history: "History",
    settings: "Settings",
    total_balance: "Total Balance",
    total_income: "Total Income",
    total_expense: "Total Expense",
    recent_activity: "Recent Activity",
    add_income: "Add Income",
    add_expense: "Add Expense",
    description: "Description",
    amount: "Amount",
    category: "Category",
    save: "Save",
    cancel: "Cancel",
    search: "Search...",
    daily_sales: "Daily Income",
    daily_expenses: "Daily Expenses",
    net_profit: "Net Balance",
    no_data: "No data available",
    today: "Today",
    
    // Categories
    Salary: "Salary",
    Rent: "Rent",
    Food: "Food",
    Transport: "Transport",
    Utilities: "Utilities",
    Medical: "Medical",
    Entertainment: "Entertainment",
    Misc: "Misc",
    Others: "Others",
    
    // Settings & Security
    profile_security: "Profile & Account Security",
    update_security_pin: "Update Security PIN",
    require_pin_deletions: "Require PIN for Deletions",
    core_parameters: "Core Parameters",
    app_language: "App Language / செயலி மொழி",
    monthly_savings_target: "Monthly Savings Target (₹)",
    category_architecture: "Category Architecture Engine",
    income_categories: "Income Categories",
    expense_categories: "Expense Categories",
    add_custom_category: "Add custom category...",
    cloud_architecture: "Cloud Architecture Synced Securely with Supabase v3.0",
    sign_out: "Sign Out",
    modify: "Modify",
    verify_identity: "Verify Identity",
    current_password: "Current Password",
    set_new_credentials: "Set New Credentials",
    new_pin: "New 4-Digit PIN",
    confirm_pin: "Confirm New PIN",
    save_pin: "Save PIN",
    confirm_action: "Confirm Action",
    enter_pin_to_delete: "Enter 4-Digit PIN to delete.",
    confirm: "Confirm"
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    analytics: "பகுப்பாய்வு",
    history: "வரலாறு",
    settings: "அமைப்புகள்",
    total_balance: "மொத்த இருப்பு",
    total_income: "மொத்த வருமானம்",
    total_expense: "மொத்த செலவு",
    recent_activity: "சமீபத்திய நடவடிக்கைகள்",
    add_income: "வருமானம் சேர்",
    add_expense: "செலவு சேர்",
    description: "விவரம்",
    amount: "தொகை",
    category: "வகை",
    save: "சேமி",
    cancel: "ரத்து செய்",
    search: "தேடு...",
    daily_sales: "தினசரி வருமானம்",
    daily_expenses: "தினசரி செலவுகள்",
    net_profit: "நிகர இருப்பு",
    no_data: "தரவு இல்லை",
    today: "இன்று",
    
    // Categories
    Salary: "சம்பளம்",
    Rent: "வாடகை",
    Food: "உணவு",
    Transport: "போக்குவரத்து",
    Utilities: "பயன்பாடுகள்",
    Medical: "மருத்துவம்",
    Entertainment: "பொழுதுபோக்கு",
    Misc: "இதர",
    Others: "மற்றவை",

    // Settings & Security
    profile_security: "சுயவிவரம் மற்றும் கணக்கு பாதுகாப்பு",
    update_security_pin: "பாதுகாப்பு பின்னை மாற்று",
    require_pin_deletions: "நீக்குவதற்கு பின் (PIN) தேவை",
    core_parameters: "முக்கிய அளவுகோல்கள்",
    app_language: "App Language / செயலி மொழி",
    monthly_savings_target: "மாதாந்திர சேமிப்பு இலக்கு (₹)",
    category_architecture: "வகைப்பாடு கட்டமைப்பு",
    income_categories: "வருமான வகைகள்",
    expense_categories: "செலவு வகைகள்",
    add_custom_category: "புதிய வகை சேர்...",
    cloud_architecture: "கிளவுட் கட்டமைப்பு சுபாபேஸுடன் பாதுகாப்பாக ஒத்திசைக்கப்பட்டது",
    sign_out: "வெளியேறு",
    modify: "மாற்று",
    verify_identity: "அடையாளத்தை உறுதிப்படுத்து",
    current_password: "தற்போதைய கடவுச்சொல்",
    set_new_credentials: "புதிய சான்றுகளை அமைக்கவும்",
    new_pin: "புதிய 4-இலக்க பின்",
    confirm_pin: "புதிய பின்னை உறுதிப்படுத்து",
    save_pin: "பின்னைக் (PIN) சேமி",
    confirm_action: "செயலை உறுதிப்படுத்து",
    enter_pin_to_delete: "நீக்க 4-இலக்க பின் (PIN) உள்ளிடவும்.",
    confirm: "உறுதிப்படுத்து"
  }
};
