export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    analytics: "Analytics",
    history: "History",
    settings: "Settings",
    total_balance: "Total Balance",
    total_income: "Total Income",
    total_expense: "Total Expense",
    recent_activity: "Recent Activity",
    add_income: "Add Income",
    add_expense: "Add Expense",
    description: "Description",
    amount: "Amount",
    category: "Category",
    save: "Save",
    cancel: "Cancel",
    search: "Search...",
    daily_sales: "Daily Income",
    daily_expenses: "Daily Expenses",
    weekly_sales: "Weekly Income",
    weekly_expenses: "Weekly Expenses",
    monthly_sales: "Monthly Income",
    monthly_expenses: "Monthly Expenses",
    net_profit: "Net Balance",
    no_data: "No data available",
    today: "Today",
    vs_yesterday: "VS. YESTERDAY",
    vs_last_week: "VS. LAST WEEK",
    vs_last_month: "VS. LAST MONTH",
    live_calculated: "LIVE CALCULATED",
    
    // Categories
    Salary: "Salary",
    "Other Income": "Other Income",
    Rent: "Rent",
    Food: "Food",
    Transport: "Transport",
    Utilities: "Utilities",
    Medical: "Medical",
    Entertainment: "Entertainment",
    Other: "Other",
    Others: "Others",
    
    // Settings & Security
    profile_security: "Profile & Account Security",
    update_security_pin: "Update Security PIN",
    require_pin_deletions: "Require PIN for Deletions",
    core_parameters: "Core Parameters",
    app_language: "App Language / செயலி மொழி",
    monthly_savings_target: "Monthly Savings Target (₹)",
    category_architecture: "Category Architecture Engine",
    income_categories: "Income Categories",
    expense_categories: "Expense Categories",
    add_custom_category: "Add custom category...",
    cloud_architecture: "Cloud Architecture Synced Securely with Supabase v3.0",
    sign_out: "Sign Out",
    modify: "Modify",
    verify_identity: "Verify Identity",
    current_password: "Current Password",
    set_new_credentials: "Set New Credentials",
    new_pin: "New 4-Digit PIN",
    confirm_pin: "Confirm New PIN",
    save_pin: "Save PIN",
    confirm_action: "Confirm Action",
    enter_pin_to_delete: "Enter 4-Digit PIN to delete.",
    confirm: "Confirm",

    // New Modals & Fields Localization
    amount_label: "Amount (₹)",
    category_label: "Category",
    select_category: "Select Category",
    date_label: "Date",
    note_label: "Note",
    optional_placeholder: "(Optional)",
    saving: "Saving...",
    income_label: "Income",
    expense_label: "Expense",
    select_category_placeholder: "Select Category...",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    end_of_month: "End of Month",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    day_placeholder: "Day (1-31)",
    add_reminder_btn: "Add Reminder",
    authenticating: "Authenticating...",
    pin_not_match: "PINs do not match",
    must_be_4_digits: "Must be 4 digits",
    incorrect_pin: "Incorrect PIN",
    current_pin: "Current PIN",
    new_pin_label: "New PIN",
    verify: "Verify",
    syncing: "Syncing...",
    clear_btn: "Clear",
    clear_all_filters: "Clear all filters",
    no_transactions: "No transactions found",
    notes_placeholder: "Notes…",
    edit_label: "Edit",
    delete_label: "Delete",
    automated_entry: "AUTOMATED ENTRY",
    no_notes: "No notes",
    unknown_date: "Unknown Date",
    overdue: "OVERDUE",
    due_today: "DUE TODAY",
    due: "due",
    mark_as_paid: "MARK AS PAID",
    financial_status: "Financial Status",
    this_vs_last_month: "This Month vs Last Month",
    income_vs_expense: "Income vs Expense",
    expenses_by_category: "Expenses by Category",
    last_month_short: "last month"
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    analytics: "பகுப்பாய்வு",
    history: "வரலாறு",
    settings: "அமைப்புகள்",
    total_balance: "மொத்த இருப்பு",
    total_income: "மொத்த வருமானம்",
    total_expense: "மொத்த செலவு",
    recent_activity: "சமீபத்திய நடவடிக்கைகள்",
    add_income: "வருமானம் சேர்",
    add_expense: "செலவு சேர்",
    description: "விவரம்",
    amount: "தொகை",
    category: "வகை",
    save: "சேமி",
    cancel: "ரத்து செய்",
    search: "தேடு...",
    daily_sales: "தினசரி வருமானம்",
    daily_expenses: "தினசரி செலவுகள்",
    weekly_sales: "வாராந்திர வருமானம்",
    weekly_expenses: "வாராந்திர செலவுகள்",
    monthly_sales: "மாதாந்திர வருமானம்",
    monthly_expenses: "மாதாந்திர செலவுகள்",
    net_profit: "நிகர இருப்பு",
    no_data: "தரவு இல்லை",
    today: "இன்று",
    vs_yesterday: "நேற்றுடன் ஒப்பிடும்போது",
    vs_last_week: "கடந்த வாரத்துடன் ஒப்பிடும்போது",
    vs_last_month: "கடந்த மாதத்துடன் ஒப்பிடும்போது",
    live_calculated: "நேரடி கணக்கீடு",
    
    // Categories
    Salary: "சம்பளம்",
    "Other Income": "இதர வருமானம்",
    Rent: "வாடகை",
    Food: "உணவு",
    Transport: "போக்குவரத்து",
    Utilities: "பயன்பாடுகள்",
    Medical: "மருத்துவம்",
    Entertainment: "பொழுதுபோக்கு",
    Other: "இதர",
    Others: "மற்றவை",

    // Settings & Security
    profile_security: "சுயவிவரம் மற்றும் கணக்கு பாதுகாப்பு",
    update_security_pin: "பாதுகாப்பு பின்னை மாற்று",
    require_pin_deletions: "நீக்குவதற்கு பின் (PIN) தேவை",
    core_parameters: "முக்கிய அளவுகோல்கள்",
    app_language: "App Language / செயலி மொழி",
    monthly_savings_target: "மாதாந்திர சேமிப்பு இலக்கு (₹)",
    category_architecture: "வகைப்பாடு கட்டமைப்பு",
    income_categories: "வருமான வகைகள்",
    expense_categories: "செலவு வகைகள்",
    add_custom_category: "புதிய வகை சேர்...",
    cloud_architecture: "கிளவுட் கட்டமைப்பு சுபாபேஸுடன் பாதுகாப்பாக ஒத்திசைக்கப்பட்டது",
    sign_out: "வெளியேறு",
    modify: "மாற்று",
    verify_identity: "அடையாளத்தை உறுதிப்படுத்து",
    current_password: "தற்போதைய கடவுச்சொல்",
    set_new_credentials: "புதிய சான்றுகளை அமைக்கவும்",
    new_pin: "புதிய 4-இலக்க பின்",
    confirm_pin: "புதிய பின்னை உறுதிப்படுத்து",
    save_pin: "பின்னைக் (PIN) சேமி",
    confirm_action: "செயலை உறுதிப்படுத்து",
    enter_pin_to_delete: "நீக்க 4-இலக்க பின் (PIN) உள்ளிடவும்.",
    confirm: "உறுதிப்படுத்து",

    // New Modals & Fields Localization
    amount_label: "தொகை (₹)",
    category_label: "வகை",
    select_category: "வகையைத் தேர்ந்தெடுக்கவும்",
    date_label: "தேதி",
    note_label: "குறிப்பு",
    optional_placeholder: "(விருப்பத்தேர்வு)",
    saving: "சேமிக்கப்படுகிறது...",
    income_label: "வருமானம்",
    expense_label: "செலவு",
    select_category_placeholder: "வகையைத் தேர்ந்தெடுக்கவும்...",
    daily: "தினசரி",
    weekly: "வாராந்திர",
    monthly: "மாதாந்திர",
    end_of_month: "மாத இறுதி",
    monday: "திங்கள்",
    tuesday: "செவ்வாய்",
    wednesday: "புதன்",
    thursday: "வியாழன்",
    friday: "வெள்ளி",
    saturday: "சனி",
    sunday: "ஞாயிறு",
    day_placeholder: "தேதி (1-31)",
    add_reminder_btn: "நினைவூட்டல் சேர்",
    authenticating: "சரிபார்க்கப்படுகிறது...",
    pin_not_match: "பின்கள் பொருந்தவில்லை",
    must_be_4_digits: "4 இலக்கங்கள் இருக்க வேண்டும்",
    incorrect_pin: "தவறான பின்",
    current_pin: "தற்போதைய பின்",
    new_pin_label: "புதிய பின்",
    verify: "சரிபார்",
    syncing: "ஒத்திசைக்கப்படுகிறது...",
    clear_btn: "வடிகட்டியை நீக்கு",
    clear_all_filters: "அனைத்து வடிகட்டிகளையும் நீக்கு",
    no_transactions: "பரிவர்த்தனைகள் எதுவும் இல்லை",
    notes_placeholder: "குறிப்புகள்...",
    edit_label: "தொகு",
    delete_label: "நீக்கு",
    automated_entry: "தானியங்கி பதிவு",
    no_notes: "குறிப்புகள் இல்லை",
    unknown_date: "தெரியாத தேதி",
    overdue: "காலக்கெடு முடிந்தது",
    due_today: "இன்று செலுத்த வேண்டும்",
    due: "செலுத்த வேண்டிய தேதி",
    mark_as_paid: "செலுத்தப்பட்டதாக குறி",
    financial_status: "நிதி நிலைமை",
    this_vs_last_month: "இந்த மாதம் vs கடந்த மாதம்",
    income_vs_expense: "வருமானம் vs செலவு",
    expenses_by_category: "வகைவாரி செலவு",
    last_month_short: "கடந்த மாதம்"
  }
};
